config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'log in', sign_out: 'log out', sign_up: 'Sign Up'}

  resources :friends
  resources :users, only: %i[show create]
  # root "home#index"
  root "friends#index"
  get "home/about"
 

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true
 

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,])
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    def correct_user
      @friend = current_user.friends.find_by(id: params[:id])
      friends_path
      redirect_to friends_path, notice: "You are do Authorized to Edit this friend" if @friend.nil?
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_us = "Welcome to Friends App."
   
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_report(resource)
    render 'devise/shared/error_messages', resource: resource if resource.errors.any?
  end

 
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
<% if friend.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

  <ul>
    <% friend.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field form-group">

  <%= form.text_field :first_name , class:"form-control", placeholder:"Firtst Name" %><br>
</div>

<div class="field form-group">

  <%= form.text_field :last_name , class:"form-control" , placeholder:"Last Name" %><br>
</div>

<div class="field form-group">

  <%= form.text_field :email, class:"form-control", placeholder:"Email" %><br>
</div>

<div class="field form-group">

  <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %><br>
</div>

<div class="field form-group">

  <%= form.text_field :twitter , class:"form-control", placeholder:"Twitter" %>
</div>
<div class="field form-group">

  <%= form.number_field :user_id ,id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
</div>
<br>
<div class="actions">
  <%= form.submit class:"btn btn-secondary"%>
</div>
<% end %>

app/views/friends/edit.html.erb
<h1>Modify Friend's info</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Show', @friend, class:"btn btn-secondary"%>
<%= link_to 'Delete', @friend, class:"btn btn-danger ", method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', friends_path, class:"btn btn-secondary"%>

app/views/friends/index.html.erb
<% if user_signed_in?%>
<div class="table-responsive">
  <table class=" table table-striped table-hover table-bordered">
    <thead class="table-dark">

      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th>User Id</th>
        <th>Un-friend</th>
      </tr>
    </thead>


    <tbody class="table-info">
      <% @friends.each do |friend| %>
      <!-- To have a user see and have access only to his own friends ----->
      <% if friend.user == current_user%>
      <tr>
        <td><%= link_to friend.first_name + " " +friend.last_name  , friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Delete', friend, class:"btn btn-outline-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%end%>
      <% end %>
    </tbody>
  </table>
</div>

<br>



<%else%>
<p>Welcome to Friends App.</p>
<p>This is application is for keeping a good record of your friends and their contacts.</p>
<p>We are currently working on adding more functionalities like:</p>
<ol>
  <li>scheduling calls</li>
  <li>Direct email messaging</li>
  <li>Social media interactions</li>
</ol>
<%end%>
<%= link_to 'Add New Friend', new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>Add New Friend</h1>
  </div>
  <div class="card-body">
    <br>
    <%= render 'form', friend: @friend %>
  </div>
</div>
<br>
<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1 class="display-4"> <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p>
    <%= link_to @friend.email %> |
    <%= link_to @friend.phone %> |
    <%= link_to @friend.twitter %>|
    <%= link_to @friend.user_id %>
  </p>
  <br>
  <p>
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
    <%= link_to 'Delete', @friend, class:"btn btn-danger ", method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Back', friends_path, class:"btn btn-secondary" %>
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friends App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>
        <!--
          <li class="nav-item">
            <%= link_to "My Friends", friends_path, class: "nav-link" %>
          </li>
          -->
        <!--
          <li class="nav-item">
            <%= link_to "Add New Friend", new_friend_path, class: "nav-link" %>
          </li>
-->
        <li class="nav-item">
          <%= link_to "log out", destroy_user_session_path, method: :DELETE, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <span class="nav-link"><%=current_user.name%> </span>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>


        <%else%>
        <li class="nav-item">
          <%= link_to "log in", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Up",   new_user_registration_path, class: "nav-link" %>
        </li>

        <%end%>
        <!--
          <li class="nav-item">
            <%= link_to "About Us", home_about_path, class: "nav-link" %>
          </li>
-->

      </ul>
      <form class="d-flex">

        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<%= @about_us%>
<p>This is application is for keeping a good record of your friends and their contacts.</p>
<p>We are currently working on adding more functionalities like:</p>
<ol>
  <li>scheduling calls</li>
  <li>Direct email messaging</li>
  <li>Social media interactions</li>
</ol>

app/views/home/users.html.erb
<h1>Users List ......</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <title>Friends App</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>


  <%= render 'home/header'%>
  <div class="container">
    <br>
    <% if notice %>
    <%= render 'layouts/alerts' %>
    <%end%>
    <br>
    <%= yield %>
  </div>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>